apiVersion: v1
kind: Service
metadata:
 name: web-loadbalancer
spec:
 type: LoadBalancer
 selector:
    app: my-web
 ports:
  - name: "80"
    port: 80
    targetPort: 80
    
  - name: "443"
    port: 443
    targetPort: 443