apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    app: web
    rel: stable
spec:
  containers:
  - name: my-web
    image: acrmarvel.azurecr.io/marveldocker_marvelweb:v1
    ports:
    - containerPort: 80
  imagePullSecrets:
    - name: acr-secret
      
# kubectl create –f nginx.pod.yml --save-config
# kubectl describe pod [pod-name]
# kubectl apply –f nginx.pod.yml
# kubectl exec [pod-name] -it sh
# kubectl edit -f nginx.pod.yml
# Kubectl delete –f nginx.pod.yml

# To exec into container use:
# kubectl exec pod-name -it sh